onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - esbuild
  - msw
  - sharp
  - unrs-resolver
peerDependencyRules:
  allowedVersions:
    react: 19.2.0
    react-dom: 19.2.0
    next: 16.0.1
  allowAny:
    - '@types/react'
    - '@types/react-dom'
