onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - msw
  - sharp
  - unrs-resolver

peerDependencyRules:
  allowAny:
    - '@types/react'
    - '@types/react-dom'
  allowedVersions:
    next: 16.0.1
    react: 19.2.0
    react-dom: 19.2.0
